### ISSUE TITLE
No such file or directory: bound/ensemble_equilibration_1/somd_1.rst7

### ISSUE THREAD

**Issue by avnikonenko** [michellab/a3fe#18]
Hello!
While running example run (files from a3fe/a3fe/data/example_run_dir) I got an error: FileNotFoundError: [Errno 2] No such file or directory: 'a3fe/test/bound/ensemble_equilibration_1/somd_1.rst7.
I checked the log file a3fe/test/bound/ensemble_equilibration_1/somd-array-gpu-1975979.4294967294.out :
```
INFO:numexpr.utils:Note: detected 128 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
INFO:numexpr.utils:Note: NumExpr detected 128 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
INFO:numexpr.utils:NumExpr defaulting to 16 threads.
Loading pre-equilibrated system...
Selecting ligand <BioSimSpace.Molecule: number=17, nAtoms=34, nResidues=1> for decoupling
Running SOMD ensemble equilibration simulation for 5000 ps
Saving somd.rst7 to .

``` 
The log output seems alright. 
The files which are in the a3fe/test/bound/ensemble_equilibration_1/ directory:
```
bound_preequil.prm7      gromacs.edr  gromacs.mdp      gromacs_ref.gro  README.txt                  
somd-array-gpu-1975980.4294967294.out
bound_preequil.rst7      gromacs.err  gromacs.out      gromacs.top      restraint_2.txt              system_preparation_config_bound.pkl
ensemble_equil_bound.sh  gromacs.gro  gromacs_out.gro  gromacs.tpr      restraint_idx0_dof_hist.png
gromacs.cpt              gromacs.log  gromacs.out.mdp  gromacs.xtc      restraint_idx0_dof_time.png

```
Could you help me please?

**Comment by fjclark** [comment]
Hi!

Sorry you've run into another issue.

I've verified that this runs fine locally for me with the latest version of the code. My slurm .out file looks identical to yours. The output in `bound/ensemble_equilibration_1` also looks the same, other than:

- I see `restraint_1.txt`, rather than `restraint_2.txt`. The number should match the number in the `ensemble_equilibration` directory.
- I have the missing file `somd_1.rst7`

The first thing I'm confused about is why your restraint is getting saved as `2` rather than `1` [here](https://github.com/michellab/a3fe/blob/95f61d24f5d66cf5fbd72a2974783975d6946cc2/a3fe/run/leg.py#L694).  This suggests that `ensemble_equilibration_1` isn't the first in `outdirs`. To check this, could you please add the line
```
self._logger.info(f"Outdirs {outdirs}")
```
below [this line](https://github.com/michellab/a3fe/blob/95f61d24f5d66cf5fbd72a2974783975d6946cc2/a3fe/run/leg.py#L671). Could you then please delete the `bound` directory, `Calculation.log` and `Calculation.pkl`, and rerun (the full set-up won't rerun as the `pre_equilibrated` files will be read from `input`)? Please then paste the `Leg.log` output. Thanks!

I'm not sure where `somd_{i}.rst7` has disappeared to. From the slurm file, it's obviously saved, and it must be saved to `ensemble_equilibration_1` otherwise you would get an error [here](https://github.com/michellab/a3fe/blob/95f61d24f5d66cf5fbd72a2974783975d6946cc2/a3fe/run/leg.py#L650). I'm assuming your error is raised [here](https://github.com/michellab/a3fe/blob/95f61d24f5d66cf5fbd72a2974783975d6946cc2/a3fe/run/leg.py#L786) but I don't see anywhere that the rst7 files could have been modified since [here](https://github.com/michellab/a3fe/blob/95f61d24f5d66cf5fbd72a2974783975d6946cc2/a3fe/run/leg.py#L650), which can't have raised an error if the restraint was generated.

Some more information might help. Could you please rerun after deleting the `bound` directory,  `Calculation.log` and `Calculation.pkl` files as suggested above and share the full outputs of `Calculation.log` and `Leg.log`?

Thanks!

**Comment by avnikonenko** [comment]
For some unclear for me reasons, everything worked well this time, I got the output file. I run before a few times and got every time the same error... maybe it was something related to our cluster system. 
I am really sorry for that.
Thank you again for the help and the tool!

**Comment by fjclark** [comment]
No problem at all! I'll close for now, but please reopen if you run into the issue again and we can debug then.
